services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '9000:8080'
    environment:
      SYSTEM_ENABLEANALYTICS: false
    volumes:
      - ./stirling-data:/configs
