---
x-defaults: &defaults
  security_opt:
    - no-new-privileges:true
services:
  stirling-pdf:
    <<: *defaults
    image: docker.io/stirlingtools/stirling-pdf:2.14.2-fat
    ports:
      - 127.0.0.1:9000:8080
    environment:
      SYSTEM_ENABLEANALYTICS: false
    volumes:
      - ./stirling-data:/configs
